//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/ChessControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ChessControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ChessControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ChessControls"",
    ""maps"": [
        {
            ""name"": ""MenuNav"",
            ""id"": ""2c15383f-a30a-472b-be8d-fc9bcfa1200b"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""a863e0bb-c38b-481e-8b67-f57c24c502f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""26724116-ce55-47a2-b606-70244045be44"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MouseInput"",
            ""id"": ""c1f8a7e5-8a7a-490d-bc45-1703750f4e13"",
            ""actions"": [
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""e1100c0b-dffb-446b-bcb4-5d51c562fa24"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""ac8d27d2-5f3e-42cb-946b-cba4c8c6020c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b6569eb6-9790-4ee5-9e9b-f201df114287"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""facf133a-a943-42ba-b9d4-9d1028705456"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MobileControls"",
            ""id"": ""e42bcd5a-c934-4f25-934a-21b7e877b6a9"",
            ""actions"": [
                {
                    ""name"": ""LeftStick"",
                    ""type"": ""Value"",
                    ""id"": ""5a23b57f-674d-4fbe-b06b-519d208628db"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStick"",
                    ""type"": ""Value"",
                    ""id"": ""fbb88ecb-559a-4372-8793-532e6158a929"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchDelta"",
                    ""type"": ""Value"",
                    ""id"": ""55862c58-3b27-496f-9937-45fce0b35d75"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""fec8263d-a984-40d2-b6f3-60056b63e7ca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fe53130e-83de-4dff-9f0e-96a77f5426a5"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75d4d72b-6b66-4cbb-8178-9e6707c44df1"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20aac8f9-fd9c-40da-a935-f9cb933e704e"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""498b5598-ce3c-45d5-819b-ae3945a10fd0"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MenuNav
        m_MenuNav = asset.FindActionMap("MenuNav", throwIfNotFound: true);
        m_MenuNav_Newaction = m_MenuNav.FindAction("New action", throwIfNotFound: true);
        // MouseInput
        m_MouseInput = asset.FindActionMap("MouseInput", throwIfNotFound: true);
        m_MouseInput_MouseDelta = m_MouseInput.FindAction("MouseDelta", throwIfNotFound: true);
        m_MouseInput_MousePosition = m_MouseInput.FindAction("MousePosition", throwIfNotFound: true);
        // MobileControls
        m_MobileControls = asset.FindActionMap("MobileControls", throwIfNotFound: true);
        m_MobileControls_LeftStick = m_MobileControls.FindAction("LeftStick", throwIfNotFound: true);
        m_MobileControls_RightStick = m_MobileControls.FindAction("RightStick", throwIfNotFound: true);
        m_MobileControls_TouchDelta = m_MobileControls.FindAction("TouchDelta", throwIfNotFound: true);
        m_MobileControls_TouchPosition = m_MobileControls.FindAction("TouchPosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MenuNav
    private readonly InputActionMap m_MenuNav;
    private IMenuNavActions m_MenuNavActionsCallbackInterface;
    private readonly InputAction m_MenuNav_Newaction;
    public struct MenuNavActions
    {
        private @ChessControls m_Wrapper;
        public MenuNavActions(@ChessControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_MenuNav_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_MenuNav; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuNavActions set) { return set.Get(); }
        public void SetCallbacks(IMenuNavActions instance)
        {
            if (m_Wrapper.m_MenuNavActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_MenuNavActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_MenuNavActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_MenuNavActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_MenuNavActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public MenuNavActions @MenuNav => new MenuNavActions(this);

    // MouseInput
    private readonly InputActionMap m_MouseInput;
    private IMouseInputActions m_MouseInputActionsCallbackInterface;
    private readonly InputAction m_MouseInput_MouseDelta;
    private readonly InputAction m_MouseInput_MousePosition;
    public struct MouseInputActions
    {
        private @ChessControls m_Wrapper;
        public MouseInputActions(@ChessControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseDelta => m_Wrapper.m_MouseInput_MouseDelta;
        public InputAction @MousePosition => m_Wrapper.m_MouseInput_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_MouseInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseInputActions set) { return set.Get(); }
        public void SetCallbacks(IMouseInputActions instance)
        {
            if (m_Wrapper.m_MouseInputActionsCallbackInterface != null)
            {
                @MouseDelta.started -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.performed -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.canceled -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnMouseDelta;
                @MousePosition.started -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnMousePosition;
            }
            m_Wrapper.m_MouseInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MouseDelta.started += instance.OnMouseDelta;
                @MouseDelta.performed += instance.OnMouseDelta;
                @MouseDelta.canceled += instance.OnMouseDelta;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
            }
        }
    }
    public MouseInputActions @MouseInput => new MouseInputActions(this);

    // MobileControls
    private readonly InputActionMap m_MobileControls;
    private IMobileControlsActions m_MobileControlsActionsCallbackInterface;
    private readonly InputAction m_MobileControls_LeftStick;
    private readonly InputAction m_MobileControls_RightStick;
    private readonly InputAction m_MobileControls_TouchDelta;
    private readonly InputAction m_MobileControls_TouchPosition;
    public struct MobileControlsActions
    {
        private @ChessControls m_Wrapper;
        public MobileControlsActions(@ChessControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftStick => m_Wrapper.m_MobileControls_LeftStick;
        public InputAction @RightStick => m_Wrapper.m_MobileControls_RightStick;
        public InputAction @TouchDelta => m_Wrapper.m_MobileControls_TouchDelta;
        public InputAction @TouchPosition => m_Wrapper.m_MobileControls_TouchPosition;
        public InputActionMap Get() { return m_Wrapper.m_MobileControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MobileControlsActions set) { return set.Get(); }
        public void SetCallbacks(IMobileControlsActions instance)
        {
            if (m_Wrapper.m_MobileControlsActionsCallbackInterface != null)
            {
                @LeftStick.started -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnLeftStick;
                @LeftStick.performed -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnLeftStick;
                @LeftStick.canceled -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnLeftStick;
                @RightStick.started -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnRightStick;
                @RightStick.performed -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnRightStick;
                @RightStick.canceled -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnRightStick;
                @TouchDelta.started -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnTouchDelta;
                @TouchDelta.performed -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnTouchDelta;
                @TouchDelta.canceled -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnTouchDelta;
                @TouchPosition.started -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnTouchPosition;
                @TouchPosition.performed -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnTouchPosition;
                @TouchPosition.canceled -= m_Wrapper.m_MobileControlsActionsCallbackInterface.OnTouchPosition;
            }
            m_Wrapper.m_MobileControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftStick.started += instance.OnLeftStick;
                @LeftStick.performed += instance.OnLeftStick;
                @LeftStick.canceled += instance.OnLeftStick;
                @RightStick.started += instance.OnRightStick;
                @RightStick.performed += instance.OnRightStick;
                @RightStick.canceled += instance.OnRightStick;
                @TouchDelta.started += instance.OnTouchDelta;
                @TouchDelta.performed += instance.OnTouchDelta;
                @TouchDelta.canceled += instance.OnTouchDelta;
                @TouchPosition.started += instance.OnTouchPosition;
                @TouchPosition.performed += instance.OnTouchPosition;
                @TouchPosition.canceled += instance.OnTouchPosition;
            }
        }
    }
    public MobileControlsActions @MobileControls => new MobileControlsActions(this);
    public interface IMenuNavActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IMouseInputActions
    {
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
    public interface IMobileControlsActions
    {
        void OnLeftStick(InputAction.CallbackContext context);
        void OnRightStick(InputAction.CallbackContext context);
        void OnTouchDelta(InputAction.CallbackContext context);
        void OnTouchPosition(InputAction.CallbackContext context);
    }
}
